
find_library(LLXGVAGATE_BASE_LIB "llxgvagate")
set(LLIUREX_GVAGATE_INCLUDE_DIRS "/usr/include/lliurex/gvagate/")
set(LLIUREX_GVAGATE_LIBRARIES ${LLXGVAGATE_BASE_LIB})

add_library(Lliurex::GvaGate SHARED IMPORTED)
set_target_properties(Lliurex::GvaGate PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES ${LLIUREX_GVAGATE_INCLUDE_DIRS}
    INTERFACE_LINK_LIBRARIES "Lliurex::GvaGate"
    IMPORTED_LOCATION ${LLIUREX_GVAGATE_LIBRARIES}
)
